### PR TITLE
Add `classifiers` table

### LINKED ISSUE #28: Add a "classifiers" table
For example, it might look something like

| package_name   | name |
|----------|--------|
| requests | Development Status :: 5 - Production/Stable |
| requests | Environment :: Web Environment |
| requests | Intended Audience :: Developers |
| requests | License :: OSI Approved :: Apache Software License |
| requests | Natural Language :: English |

I don't see any intention of normalizing the db, so I think this would be the desired approach.

The `classifiers` array seems to be generally available in `$.info.classifiers` as part of PyPI's JSON API: https://pypi.org/pypi/requests/json

I can submit a PR if this something you consider valuable.

### PR DESCRIPTION
**Pull request by edgarrmondragon**
Closes https://github.com/sethmlarson/pypi-data/issues/28

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
This is an example query

```sql
select name, count(distinct package_name) from classifiers where name like 'Programming Language :: Python :: 3%' group by 1 order by 2 desc;
```


|                    name                     | count(distinct package_name) |
|---------------------------------------------|------------------------------|
| Programming Language :: Python :: 3         | 254803                       |
| Programming Language :: Python :: 3.8       | 99431                        |
| Programming Language :: Python :: 3.9       | 93880                        |
| Programming Language :: Python :: 3.7       | 86250                        |
| Programming Language :: Python :: 3.10      | 80917                        |
| Programming Language :: Python :: 3.6       | 78359                        |
| Programming Language :: Python :: 3.11      | 60005                        |
| Programming Language :: Python :: 3.5       | 46703                        |
| Programming Language :: Python :: 3.4       | 35560                        |
| Programming Language :: Python :: 3 :: Only | 29212                        |
| Programming Language :: Python :: 3.12      | 26282                        |
| Programming Language :: Python :: 3.3       | 15959                        |
| Programming Language :: Python :: 3.2       | 5643                         |
| Programming Language :: Python :: 3.1       | 1498                         |
| Programming Language :: Python :: 3.13      | 1404                         |
| Programming Language :: Python :: 3.0       | 1083                         |

**Comment by jonathan-s** [comment]
Also interested in getting this into the dataset.

**Comment by jonathan-s** [comment]
Also code looks good to me!

**Comment by edgarrmondragon** [comment]
Ping @sethmlarson :)

**Review by sethmlarson — APPROVED** [review]
I'll try seeing how this affects the database size.

**Pull request merged**
